server:
  port: 8044
spring:
  application:
    name: alibaba-seata-storage
  cloud:
    nacos:
      discovery:
        enabled: true
        service: ${spring.application.name}
        server-addr: localhost:1111  #配置nacos地址
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
  datasource:
    #当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    #mysql驱动包
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.200.144:3306/seata-storage?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
feign:
  hystrix:
    enabled: true
mybatis:
  mapperLocations: classpath:mapper/*.xml
  #所有entity别名类所在包
  type-aliases-package: com.alibaba.seata.storage.entity
management: #暴露监控端点
  endpoints:
    web:
      exposure:
        include: "*"