server:
  port: 3344

spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jiandequn/springcloud-test
          search-paths: springcloud-config  #搜索目录
          password: jiandequn928
          username: jiandequn
          timeout: 120
          basedir: G:/git_resp
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#          skip-ssl-validation: false
#          force-pull: true
#          basedir: file:///G:/code/github_repositories/springcloud-test
#          repos:
#            local:
#              pattern: local*
#              uri: file:///G:/code/github_repositories/springcloud-test/springcloud-config
#      label: master  #读取分支

eureka:
  client:
    #是否将自己注册到注册中心, 默认true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息,单机无所谓,集群必须设置为true配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka  #单机版
  #      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
  instance:
    instance-id: ${spring.application.name}
#    #访问路径可以显示IP地址
    prefer-ip-address: true
    #Eureka客户端向服务端发送心跳的时间间隔.单位为秒(默认30 秒)
    lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次心跳等待时间上限.单位为秒(默认90 秒),超时将剔除服务
    lease-expiration-duration-in-seconds: 2

#rabbitmq相关配置，暴露bus 刷新配置端点
management:
  endpoints: #暴露bus 刷新配置的端点
    web:
      exposure:
        include: "bus-refresh"