server:
  port: 9525
spring:
  application:
    name: cloud-gateway-server03
  cloud:
    gateway:
      routes:
        - id: payment_routh #路由ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://CLOUD-PAYMENT-SERVICE  #匹配后提供注册中心服务的路由地址
          predicates:                  #断言，路径相匹配的进行路由
            - Path=/payment/get/**
        - id: payment_routh2
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/get2/**
            - Cookie=erliuzi, jshy

eureka:
  instance:
    hostname: localhost   #eureka服务端的实例名称
  client:
    register-with-eureka: true #false表示不向注册中心注册自己
    fetch-registry: true  #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url: #设置与Eureka server的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://localhost:7001/eureka/ #单机版
      #      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版

