server:
  port: 8401
spring:
  application:
    name: alibaba-sentinel-server
  cloud:
    nacos:
      discovery:
        enabled: true
        service: ${spring.application.name}
        server-addr: localhost:8848  #配置nacos地址
    sentinel:
      transport:
        dashboard: localhost:8081
        port: 8719 #默认8719，如果被占用，默认依次+1扫描，直到找到未占用的端口为止

management: #暴露监控端点
  endpoints:
    web:
      exposure:
        include: "*"