server:
  port: 80
spring:
  application:
    name: cloud-comsumer-order


eureka:
  client:
    #是否将自己注册到注册中心, 默认true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息,单机无所谓,集群必须设置为true配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka  #单机版
  #      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
  instance:
    instance-id: comsumer-order01
#    #访问路径可以显示IP地址
    prefer-ip-address: true
    #Eureka客户端向服务端发送心跳的时间间隔.单位为秒(默认30 秒)
    lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次心跳等待时间上限.单位为秒(默认90 秒),超时将剔除服务
    lease-expiration-duration-in-seconds: 2

#设置feign客户端超时时间（openFeign默认支持ribbon）
ribbon:
  ReadTimeout:  5000  #指的是建立连接所用时间，适用于网络状况正常的情况下，两端连接所用的时间,默认为1秒
  ConnectTimeout: 5000 #指的是建立连接后从服务器读取到可用资源所用的时间,默认1秒
  MaxAutoRetries: 1   #同一台实例的最大重试次数，但是不包括首次调用，默认为1次
  MaxAutoRetriesNextServer: 0 #重试负载均衡其他实例的最大重试次数，不包括首次调用，默认为0次
  OkToRetryOnAllOperations: false #是否对所有操作都重试，默认false
logging:
  level: #feign日志以什么级别监控哪个接口
    com.cloudtest.comsumer.service.PaymentFeignService:  debug

feign:
  hystrix:
    enabled: true #在Feign中开启Hystrix